### ISSUE TITLE
Issue with recursive dependencies 

### ISSUE THREAD

**Issue by IlfirinPL** [MarketSquare/robotframework-sherlock#61] opened 2022-05-12 12:08 UTC
In scenario all Resource and Library are included in file base.resource 

And resources all have included base.resource ( this way all resource have access to all keywords and variables)

```
*** Settings ***
Resource    ../base.resource
```

It cause error "RecursionError: maximum recursion depth exceeded while calling a Python object"

```
Traceback (most recent call last):
  File "C:\Python310\lib\pathlib.py", line 623, in __str__
    return self._str
AttributeError: 'WindowsPath' object has no attribute '_str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\sherlock.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\sherlock\__init__.py", line 19, in run_cli
    raise err
  File "C:\Python310\lib\site-packages\sherlock\__init__.py", line 9, in run_cli
    runner.run()
  File "C:\Python310\lib\site-packages\sherlock\core.py", line 37, in run
    suite.visit(code_visitor)
  File "C:\Python310\lib\site-packages\robot\model\testsuite.py", line 263, in visit
    visitor.visit_suite(self)
  File "C:\Python310\lib\site-packages\sherlock\visitor.py", line 36, in visit_suite
    suite.suites.visit(self)
  File "C:\Python310\lib\site-packages\robot\model\itemlist.py", line 65, in visit
    item.visit(visitor)
  File "C:\Python310\lib\site-packages\robot\model\testsuite.py", line 263, in visit
    visitor.visit_suite(self)
  File "C:\Python310\lib\site-packages\sherlock\visitor.py", line 28, in visit_suite
    suite.setup.visit(self)
  File "C:\Python310\lib\site-packages\robot\model\keyword.py", line 115, in visit
    visitor.visit_keyword(self)
  File "C:\Python310\lib\site-packages\sherlock\visitor.py", line 46, in visit_keyword
    found = self.search_scope[-1].search(name, self.resources, libname)
  File "C:\Python310\lib\site-packages\sherlock\model.py", line 366, in search
    found += resources[resource].search(name, resources, libname)
  File "C:\Python310\lib\site-packages\sherlock\model.py", line 366, in search
    found += resources[resource].search(name, resources, libname)
  File "C:\Python310\lib\site-packages\sherlock\model.py", line 366, in search
    found += resources[resource].search(name, resources, libname)
  [Previous line repeated 973 more times]
  File "C:\Python310\lib\site-packages\sherlock\model.py", line 365, in search
    resources[resource].init_imports(self.current_variables)
  File "C:\Python310\lib\site-packages\sherlock\model.py", line 350, in init_imports
    self.imported_resources.append(str(Path(self.directory, resource).resolve()))  # FIXME
  File "C:\Python310\lib\pathlib.py", line 1075, in resolve
    s = self._accessor.realpath(self, strict=strict)
  File "C:\Python310\lib\ntpath.py", line 639, in realpath
    path = normpath(path)
  File "C:\Python310\lib\ntpath.py", line 465, in normpath
    path = os.fspath(path)
  File "C:\Python310\lib\pathlib.py", line 630, in __fspath__
    return str(self)
  File "C:\Python310\lib\pathlib.py", line 625, in __str__
    self._str = self._format_parsed_parts(self._drv, self._root,
  File "C:\Python310\lib\pathlib.py", line 609, in _format_parsed_parts
    return drv + root + cls._flavour.join(parts[1:])
RecursionError: maximum recursion depth exceeded while calling a Python object
Fatal exception occurred. You can create an issue at https://github.com/bhirsz/robotframework-sherlock/issues . Thanks!
```

**Comment by bhirsz** [comment] 2022-05-14 15:17
I can reproduce it - I will take a look.

**Comment by bhirsz** [comment] 2022-05-15 07:51
Interesting problem that helped to notice we have major problems in main algorithm responsible for searching for resources (and it's causing few other bugs as well). Just short example - it's not recursive import but helps to understand how imports works in Robot Framework. For every suite RF creates separate namespace and always start searching for keyword definition from top of the namespace. 

With such files:
```
suite.robot
a.resource
```
where suite.robot:
```
*** Settings ***
Resource    a.resource


*** Test Cases ***
Test
    Keyword


*** Keywords ***
Duplicated
    Log  From suite

```

a.resource:
```
*** Keywords ***
Keyword
    Duplicated

Duplicated
    Log  From resource

```

Keyword from a.resource calls "Duplicated" keyword. Even if such keyword is defined in the same file it will take definition from suite.robot - because it's detected first when searching for keyword definition (always from top of the namespace, in this case suite.robot). 

I'm reworking our algorithm to adjust for that.

**Comment by IlfirinPL** [comment] 2022-05-15 10:58
There is similar issue when one Suite use for example SSH Library and second have Telnet Library, same names but different "namespace"

**Comment by bhirsz** [comment] 2022-05-16 06:54
Merged PR into main. Can you check if the issue is still happening? (or if something else didn't came up now - it was major change to our core code).

**Comment by IlfirinPL** [comment] 2022-05-16 06:59
I can confirm that issue is solved now

**Closed** 2022-05-16 07:07 UTC
Labels: bug
